Task 1 complite
js-tasks-ru/js-20210309-2_mount pull request #1
Opened 2021-03-11 13:51 UTC by Mountcode

2021-03-11 13:51 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 01-intro/1-sum/index.test.js — добавлен
```

2021-03-12 13:58 UTC, dosandk commented on 01-intro/1-sum/README.md
> +# Первая задача
этого файла не должно быть в PR

2021-03-12 13:59 UTC, dosandk commented on 01-intro/1-sum/index.js
> +  return m + n;
good 👍

2021-03-12 13:59 UTC, dosandk approved these changes
good 👍

2021-03-12 13:59 UTC, jsru commented
К сожалению, PR не может быть замержен, dosandk вероятно сможет помочь.

2021-03-12 13:59 UTC, dosandk commented
@Mountcode необходимо убрать системные файлы из PR

2021-03-14 14:26 UTC, dosandk approved these changes

2021-03-14 14:26 UTC, jsru commented
К сожалению, PR не может быть замержен, dosandk вероятно сможет помочь.

2021-03-16 20:29 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let sortedArr = arr.slice();
проверьте, тут точно `let`?

2021-03-16 20:29 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortedArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-03-16 20:29 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let filteredObject = Object.fromEntries(
проверьте, тут точно `let`?

2021-03-16 20:29 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let filteredObject = Object.fromEntries(
проверьте, тут точно `let`?

2021-03-16 20:30 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-03-19 14:21 UTC, dosandk approved these changes

2021-03-19 14:22 UTC, merged